stages:

  load_data:
    cmd: python load_data.py
    deps:
    - data/raw
    outs:
    - data/processed:
        cache: true
        persist: true
    - data/processed_files.txt:
        cache: false
        persist: true
    always_changed: true

  prepare_data:
    cmd: python prepare_data.py
    deps:
    - prepare_data.py
    - data/processed_files.txt
    outs:
    - data/features.csv

  train_rf:
    cmd: python train_rf.py
    deps:
    - data/features.csv
    outs:
    - models/model_rf.pkl

  train_lr:
    cmd: python train_lr.py
    deps:
    - data/features.csv
    - train_lr.py
    outs:
    - models/model_lr.pkl

  evaluate:
    cmd: python evaluate_models.py
    deps:
    - models/model_rf.pkl
    - models/model_lr.pkl
    metrics:
    - reports/metrics_report.json

plots:
- reports/train_lr/plots/metrics:
    x: step
- reports/train_lr/plots/custom/errors_vs_leafs.json:
    template: simple
    x: Max Leaf Nodes
    y: Error
    title: "LR: Errors vs Max Leaf Nodes"
- reports/train_rf/plots/metrics/Error.tsv:
    template: simple
    x: step
    y: Error
    title: "RF: Errors vs Max Leaf Nodes"
- dvclive_error_vs_nodes:
    template: simple
    x: 
      reports/dvclive/plots/metrics/Error.tsv: Error
    y: 
      reports/dvclive/plots/metrics/Max_Leaf_Nodes.tsv: Max_Leaf_Nodes
    title: "DVCLive: Errors vs Max Leaf Nodes"
metrics:
- reports/train_rf/metrics.json
- reports/train_lr/metrics.json
