stages:

  load_data:
    cmd: python load_data.py
    deps:
      - data/raw
    outs:
      - data/processed:
          cache: true
          persist: true
      - data/processed_files.txt:
          cache: false
          persist: true
    always_changed: true

  prepare_data:
    cmd: python prepare_data.py
    deps:
      - prepare_data.py
      - data/processed_files.txt
    outs:
      - data/features.csv

  train_rf:
    cmd: python train_rf.py
    deps:
      - data/features.csv
    outs:
      - models/model_rf.pkl

  train_lr:
    cmd: python train_lr.py
    deps:
      - data/features.csv
    outs:
      - models/model_lr.pkl

  evaluate:
    cmd: python evaluate_models.py
    deps:
      - models/model_rf.pkl
      - models/model_lr.pkl
    metrics:
      - reports/metrics_report.json
