stages:
  data:
    cmd: python prepare_data.py
    deps:
    - prepare_data.py
    outs:
    - data/features.csv

  train_rf:
    cmd: python train_rf.py
    deps:
    - data/features.csv
    # outs:
    #   - models/model_rf.pkl

  train_lr:
    cmd: python train_lr.py
    deps:
    - data/features.csv
    # outs:
    #   - models/model_lr.pkl

  evaluate:
    cmd: python evaluate_models.py
    deps:
    - models/model_rf.pkl
    - models/model_lr.pkl
    metrics:
    - reports/metrics_report.json
artifacts:
  model_LR:
    path: models/model_LR.pkl
    type: model
    labels:
    - lr
  model_RF:
    path: models/model_RF.pkl
    type: model
    labels:
    - rf
